version: '3.7'

services:

  app:
    container_name: wk-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '9090:9090'
    environment:
      - NODE_ENV=development